#!/bin/bash

git submodule init
git submodule update

not_ignored() {
  local ignorelist=(setup update README.md com.camthompson.macos.updateip.plist karabiner)
  for i in "${ignorelist[@]}"; do
    if [ "$1" = "$i" ]; then
      return 1
    fi
  done

  return 0
}

mkdir -p "$HOME/.config"
ln -sf "$PWD/karabiner" "$HOME/.config"
ln -sf "$PWD/nvim" "$HOME/.config"
ln -sf "$PWD/ghostty" "$HOME/.config"
ln -sf "$PWD/starship.toml" "$HOME/.config/starship.toml"
ln -sf "$PWD/borders" "$HOME/.config"
ln -sf "$PWD/bat" "$HOME/.config"
ln -sf "$PWD/eza" "$HOME/.config"
ln -sf "$PWD/lsd" "$HOME/.config"

for f in *; do
  if not_ignored "$f"; then
    rm -rf "$HOME/.$f"
    ln -s "$PWD/$f" "$HOME/.$f"
  fi
done
