#!/bin/bash

git submodule init
git submodule update
git clone https://github.com/folke/tokyonight.nvim.git ~/src/tokyonight.nvim
cp ~/src/tokyonight.nvim/extras/ghostty/tokyonight* ghostty/themes
git clone https://github.com/catppuccin/ghostty.git ~/src/catppuccin-ghostty
cp ~/src/catppuccin-ghostty/themes/* ghostty/themes

not_ignored() {
  local ignorelist=(setup update README.md com.camthompson.macos.updateip.plist karabiner coc)
  for i in "${ignorelist[@]}"; do
    if [ "$1" = "$i" ]; then
      return 1
    fi
  done

  return 0
}

mkdir -p "$HOME/.config"
ln -sf "$PWD/karabiner" "$HOME/.config"
ln -sf "$PWD/coc" "$HOME/.config"
ln -sf "$PWD/nvim" "$HOME/.config"
ln -sf "$PWD/ghostty" "$HOME/.config"
ln -sf "$PWD/starship.toml" "$HOME/.config/starship.toml"

for f in *; do
  if not_ignored "$f"; then
    rm -rf "$HOME/.$f"
    ln -s "$PWD/$f" "$HOME/.$f"
  fi
done
