#!/usr/bin/env ruby

Dir['zsh/bundle/*'].each do |d|
  Dir.chdir(d) do
    `git pull`
  end
end

`git pull`

def push_to_github()
  `git add zsh/bundle`
  `git commit -m 'ZSH plugin update'`
  `git push`
end

push_to_github unless `git status` =~ /nothing to commit/
